theme:
  active: "150, 205, 251" # current playing song in list is Blue
  banner: "150, 205, 251 	" # the "spotify-tui" banner on launch is Blue
  error_border: "242, 143, 173" # error dialog border is Red
  error_text: "232, 162, 175" # error message text (e.g. "Spotify API reported error 404") is Maroon
  hint: "250, 227, 176" # hint text in errors Yellow
  hovered: "221, 182, 242" # hovered pane border Pink
  inactive: "217, 224, 238" # borders of inactive panes White
  playbar_background: "87, 82, 104" # background of progress bar Black 4
  playbar_progress: "171, 233, 179" # filled-in part of the progress bar Green
  playbar_progress_text: "30, 30, 46" # song length and time played/left indicator in the progress bar Black 2
  playbar_text: "217, 224, 238" # artist name in player pane is White
  selected: "150, 205, 251" # a) selected pane border, b) hovered item in list, & c) track title in player Blue
  text: "217, 224, 238" # text in panes is White
  header: "150, 205, 251" # header text in panes (e.g. 'Title', 'Artist', etc.) is Blue

